[package]
name = "fp_lib"
version = "0.3.0"
edition = "2021"
license = "GPL-3.0"
description = "A library for useful things"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
