[package]
name = "fp_lib"
version = "0.6.0"
edition = "2021"
license = "MIT"
description = "A library of useful things"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
